const fs = require('fs');
const path = require('path');
const vm = require('vm');

const root = path.resolve(__dirname, '..');
const siteConfig = JSON.parse(fs.readFileSync(path.join(root, 'locales', 'site.json'), 'utf8'));
const baseUrl = String(siteConfig.baseUrl).replace(/\/+$/, '');
const locales = siteConfig.locales.map((slug) => (
    JSON.parse(fs.readFileSync(path.join(root, 'locales', slug, 'seo.json'), 'utf8'))
));
// Cloudflare Pages 정식 URL. 루트의 about.html 은 /about 으로 서빙되고
// /about.html 은 308 로 리다이렉트됩니다. hreflang·sitemap 은 200 을 주는 쪽을 써야 합니다.
const pages = [
    { key: 'home', legacyPath: '/' },
    { key: 'about', legacyPath: '/about' },
    { key: 'guide', legacyPath: '/guide' },
    { key: 'contact', legacyPath: '/contact' },
    { key: 'privacy', legacyPath: '/privacy' },
    { key: 'terms', legacyPath: '/terms' }
];
const generatedMarker = 'Generated by tools/build-multilingual-seo.js';

function loadContentTranslations() {
    const sandbox = { window: {} };
    sandbox.globalThis = sandbox.window;
    vm.createContext(sandbox);
    vm.runInContext(fs.readFileSync(path.join(root, 'content-translations.js'), 'utf8'), sandbox);
    return sandbox.window.TENTEN_CONTENT_TRANSLATIONS;
}

function getAttribute(tag, name) {
    const escapedName = name.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    const match = tag.match(new RegExp(`\\s${escapedName}\\s*=\\s*(["'])(.*?)\\1`, 'i'));
    return match ? match[2] : '';
}

function localizedPath(locale, pageKey) {
    return pageKey === 'home' ? `/${locale.slug}/` : `/${locale.slug}/${pageKey}/`;
}

function outputPath(locale, pageKey) {
    return pageKey === 'home'
        ? path.join(root, locale.slug, 'index.html')
        : path.join(root, locale.slug, pageKey, 'index.html');
}

function expectedAlternates(page) {
    return [
        ...locales.map((locale) => [locale.hreflang, `${baseUrl}${localizedPath(locale, page.key)}`]),
        ['x-default', `${baseUrl}${page.legacyPath}`]
    ];
}

function assert(condition, message) {
    if (!condition) throw new Error(message);
}

function escapeHtml(value) {
    return String(value ?? '')
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;')
        .replace(/'/g, '&#39;');
}

const contentTranslations = loadContentTranslations();
let htmlCount = 0;

for (const locale of locales) {
    for (const page of pages) {
        const filePath = outputPath(locale, page.key);
        assert(fs.existsSync(filePath), `Missing generated page: ${path.relative(root, filePath)}`);
        const html = fs.readFileSync(filePath, 'utf8');
        htmlCount += 1;

        assert(html.includes(generatedMarker), `Missing generated marker: ${path.relative(root, filePath)}`);
        const localizedSocialImage = `${baseUrl}/assets/social/og-image-${locale.slug}.png`;
        assert(html.includes(`property="og:image" content="${localizedSocialImage}"`), `Wrong social image for ${locale.slug}/${page.key}`);
        assert(html.includes(`name="twitter:image" content="${localizedSocialImage}"`), `Wrong Twitter image for ${locale.slug}/${page.key}`);
        assert(new RegExp(`<html\\b[^>]*lang=["']${locale.htmlLang}["']`, 'i').test(html), `Wrong lang for ${locale.slug}/${page.key}`);
        assert(new RegExp(`<html\\b[^>]*dir=["']${locale.dir}["']`, 'i').test(html), `Wrong dir for ${locale.slug}/${page.key}`);
        assert(/<base\s+href=["']\/["']>/i.test(html), `Missing root base href for ${locale.slug}/${page.key}`);
        assert(html.includes(`window.__TENTEN_STATIC_INTERFACE_LANGUAGE__ = ${JSON.stringify(locale.code)}`), `Missing static locale bootstrap for ${locale.slug}/${page.key}`);

        const canonicalTag = (html.match(/<link\b[^>]*rel=["']canonical["'][^>]*>/i) || [])[0] || '';
        const expectedCanonical = `${baseUrl}${localizedPath(locale, page.key)}`;
        assert(getAttribute(canonicalTag, 'href') === expectedCanonical, `Wrong canonical for ${locale.slug}/${page.key}`);

        const alternateTags = html.match(/<link\b[^>]*data-tenten-static-hreflang[^>]*>/gi) || [];
        assert(alternateTags.length === locales.length + 1, `Wrong hreflang count for ${locale.slug}/${page.key}`);
        const alternateMap = new Map(alternateTags.map((tag) => [getAttribute(tag, 'hreflang'), getAttribute(tag, 'href')]));
        for (const [hreflang, href] of expectedAlternates(page)) {
            assert(alternateMap.get(hreflang) === href, `Wrong ${hreflang} alternate for ${locale.slug}/${page.key}`);
        }

        assert(!/href=["'](?:\.\/)?(?:index|about|guide|contact|privacy|terms)\.html/i.test(html), `Legacy internal link remains in ${locale.slug}/${page.key}`);
        if (page.key === 'home') {
            assert(html.includes(`<title>${locale.homeTitle}</title>`), `Wrong home title for ${locale.slug}`);
            assert(html.includes('data-tenten-generated-schema'), `Missing SoftwareApplication schema for ${locale.slug}`);
            assert(new RegExp(`data-i18n=["']appTitle["'][^>]*>[^<]+<`, 'i').test(html), `Home app title is not pre-rendered for ${locale.slug}`);
        } else if (locale.code !== 'ko') {
            const translatedPage = contentTranslations.pages[locale.code][page.key];
            assert(html.includes(`<h1 id="${page.key === 'about' ? 'about-tentenquiz-title' : page.key === 'guide' ? 'learning-guide-title' : page.key === 'contact' ? 'contact-support-title' : page.key === 'privacy' ? 'privacy-policy-title' : 'terms-of-service-title'}">${escapeHtml(translatedPage.title)}</h1>`), `Translated H1 is missing for ${locale.slug}/${page.key}`);
            assert(html.includes(escapeHtml(translatedPage.intro)), `Translated intro is missing for ${locale.slug}/${page.key}`);
        }
    }
}

for (const page of pages) {
    const sourceFile = page.key === 'home' ? 'index.html' : `${page.key}.html`;
    const sourceHtml = fs.readFileSync(path.join(root, sourceFile), 'utf8');
    const tags = sourceHtml.match(/<link\b[^>]*data-tenten-static-hreflang[^>]*>/gi) || [];
    assert(tags.length === locales.length + 1, `Legacy ${sourceFile} is missing static hreflang links`);
    const alternateMap = new Map(tags.map((tag) => [getAttribute(tag, 'hreflang'), getAttribute(tag, 'href')]));
    for (const [hreflang, href] of expectedAlternates(page)) {
        assert(alternateMap.get(hreflang) === href, `Legacy ${sourceFile} has the wrong ${hreflang} alternate`);
    }
}

const sitemap = fs.readFileSync(path.join(root, 'sitemap.xml'), 'utf8');
assert(sitemap.includes('xmlns:xhtml="http://www.w3.org/1999/xhtml"'), 'Sitemap is missing the XHTML namespace');
const urlBlocks = sitemap.match(/<url>[\s\S]*?<\/url>/g) || [];
assert(urlBlocks.length === pages.length * (locales.length + 1), `Expected 78 sitemap URLs, received ${urlBlocks.length}`);
const sitemapLocations = new Set();
for (const block of urlBlocks) {
    const locationMatch = block.match(/<loc>(.*?)<\/loc>/);
    assert(locationMatch, 'A sitemap URL has no loc');
    sitemapLocations.add(locationMatch[1]);
    const links = block.match(/<xhtml:link\b[^>]*\/>/g) || [];
    assert(links.length === locales.length + 1, `Wrong alternate count in sitemap block ${locationMatch[1]}`);
}
assert(sitemapLocations.size === urlBlocks.length, 'Sitemap contains duplicate canonical URLs');
for (const page of pages) {
    assert(sitemapLocations.has(`${baseUrl}${page.legacyPath}`), `Sitemap is missing x-default ${page.key}`);
    for (const locale of locales) {
        assert(sitemapLocations.has(`${baseUrl}${localizedPath(locale, page.key)}`), `Sitemap is missing ${locale.slug}/${page.key}`);
    }
}

const globalConfig = fs.readFileSync(path.join(root, 'global-config.js'), 'utf8');
const contentPages = fs.readFileSync(path.join(root, 'content-pages.js'), 'utf8');
assert(globalConfig.includes('__TENTEN_STATIC_INTERFACE_LANGUAGE__'), 'The app does not honor static locale routes');
assert(globalConfig.includes('__TENTEN_STATIC_LOCALE_PATHS__'), 'The app cannot switch static locale routes');
assert(globalConfig.includes("url.pathname = `/${localizedSlug}/`"), 'The default home cannot switch to a static locale route');
assert(contentPages.includes('__TENTEN_STATIC_INTERFACE_LANGUAGE__'), 'Content pages do not honor static locale routes');
assert(contentPages.includes('data-tenten-static-hreflang'), 'Content pages may duplicate static hreflang links');

// 배포 타깃이 Cloudflare Pages 로 바뀌었으므로 firebase.json 대신 _headers / _redirects 를 검사합니다.
const headers = fs.readFileSync(path.join(root, '_headers'), 'utf8');
assert(headers.includes('/service-worker.js'), 'Cloudflare _headers must control service worker caching');

const redirects = fs.readFileSync(path.join(root, '_redirects'), 'utf8');
for (const legacyPath of ['/about', '/guide', '/contact', '/privacy', '/terms']) {
    const redirected = redirects.split(/\r?\n/).some((line) => {
        const trimmed = line.trim();
        return trimmed && !trimmed.startsWith('#') && trimmed.split(/\s+/)[0] === legacyPath;
    });
    assert(!redirected, `${legacyPath} must stay a 200 response: it is the hreflang="x-default" target`);
}

// 소셜 미리보기 태그가 생성된 72개 페이지와 루트 legacy 페이지 전부에 들어갔는지.
// 카카오톡은 og:image 가 없으면 미리보기를 아예 렌더링하지 않습니다.
const socialTargets = [];
for (const locale of locales) {
    for (const page of pages) socialTargets.push(outputPath(locale, page.key));
}
for (const legacyFile of ['index.html', 'about.html', 'guide.html', 'contact.html', 'privacy.html', 'terms.html']) {
    socialTargets.push(path.join(root, legacyFile));
}
for (const file of socialTargets) {
    const html = fs.readFileSync(file, 'utf8');
    assert(/property=["']og:image["']/i.test(html), `og:image is missing in ${path.relative(root, file)}`);
    assert(/name=["']twitter:card["']/i.test(html), `twitter:card is missing in ${path.relative(root, file)}`);
}

assert(fs.readFileSync(path.join(root, 'index.html'), 'utf8').includes(`${baseUrl}/assets/social/og-image-en.png`), 'The x-default home must use the English social image');
for (const legacyFile of ['about.html', 'guide.html', 'contact.html', 'privacy.html', 'terms.html']) {
    assert(fs.readFileSync(path.join(root, legacyFile), 'utf8').includes(`${baseUrl}/assets/social/og-image-ko.png`), `${legacyFile} must use the Korean social image`);
}

for (const locale of locales) {
    const imagePath = path.join(root, 'assets', 'social', `og-image-${locale.slug}.png`);
    assert(fs.existsSync(imagePath), `Localized social image is missing: ${locale.slug}`);
    const image = fs.readFileSync(imagePath);
    assert(image.length >= 24 && image.toString('ascii', 1, 4) === 'PNG', `Localized social image is not a PNG: ${locale.slug}`);
    assert(image.readUInt32BE(16) === 1200 && image.readUInt32BE(20) === 630, `Wrong social image dimensions: ${locale.slug}`);
}

console.log(`OK: ${htmlCount} localized pages have static translations, canonical URLs, and reciprocal hreflang links`);
console.log(`OK: sitemap.xml contains ${urlBlocks.length} unique canonical URLs with 13 language alternatives each`);
console.log('OK: localized app and content-page language switches use directory URLs');
console.log('OK: Cloudflare _headers/_redirects keep legacy x-default paths at 200');
console.log(`OK: og:image and twitter:card present on all ${socialTargets.length} pages`);
console.log(`OK: ${locales.length} localized social images are 1200x630 PNG files`);
